version: 2
updates:
  - package-ecosystem: 'npm'
    directory: 'apps/v1/app/frontend/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: 'apps/v1/app/backend/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
