apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - protocol: 'TCP'
      name: http-metrics
      port: 80
      targetPort: 3000
  selector:
    app: backend
